/**
 * Builds src/components/icons.generated.ts from the icons the source uses.
 *
 * The Flutter app draws Material Icons — `Icons.x_rounded` is the Round set,
 * `Icons.x_outlined` the Outlined set — and these are the same glyphs, from
 * Google's own SVG export. Only icons actually referenced are written out, as
 * inline path data: no icon font to download, no sprite, no runtime
 * dependency, and nothing a vendor pays for that is never drawn.
 *
 * Usage in source: <Icon name="round/chevron_right" />. Runs before every dev
 * start and build, so a new icon is picked up just by using it.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const src = join(root, 'src')
const set = join(root, 'node_modules', '@material-design-icons', 'svg')
const out = join(src, 'components', 'icons.generated.ts')

const pattern = /['"`](round|outlined|filled)\/([a-z0-9_]+)['"`]/g

function walk(dir, files = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) walk(path, files)
    else if (/\.(ts|tsx)$/.test(entry.name) && path !== out) files.push(path)
  }
  return files
}

const names = new Set()
for (const file of walk(src)) {
  for (const match of readFileSync(file, 'utf8').matchAll(pattern)) {
    names.add(`${match[1]}/${match[2]}`)
  }
}

const missing = []
const lines = [...names].sort().map((name) => {
  const file = join(set, `${name}.svg`)
  if (!existsSync(file)) {
    missing.push(name)
    return ''
  }
  const inner = readFileSync(file, 'utf8')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/'/g, '"')
    .trim()
  return `  '${name}': '${inner}',`
})

if (missing.length) {
  console.error(`gen-icons: no such Material icon: ${missing.join(', ')}`)
  process.exit(1)
}

const body = `// Generated by scripts/gen-icons.mjs from @material-design-icons/svg. Do not edit.
export const ICONS = {
${lines.join('\n')}
} as const

export type IconName = keyof typeof ICONS
`

if (!existsSync(out) || readFileSync(out, 'utf8') !== body) {
  writeFileSync(out, body)
  console.log(`gen-icons: ${names.size} icons`)
}
